version: '2'

services:
  # apigw service
  apigw:
    image: registry.cn-shenzhen.aliyuncs.com/go_micro/apigw:v1.0
    container_name: apigw
    networks:
      - web
    ports:
      - "8091:8091"
    environment:
      - PARAMS=-p 8091 --registry etcd --registry_address etcd1:2379
    labels:
      # traefik固定，与traefik设置的container_name无关
      # apigw 是 container_name
      - "traefik.enable=true" # 必填 否则无法加入traefik
      - "traefik.http.routers.apigw.rule=Host(`apigw.guaosi.com`)" # 外部域名请求
      - "traefik.http.services.apigw.loadbalancer.server.port=8091" # 转发至本容器指定port

  apigw2:
    image: registry.cn-shenzhen.aliyuncs.com/go_micro/apigw:v1.0
    container_name: apigw2
    networks:
      - web
    ports:
      - "8092:8092"
    environment:
      - PARAMS=-p 8092 --registry etcd --registry_address etcd1:2379
    labels:
      # traefik固定，与traefik设置的container_name无关
      # apigw 是 container_name
      - "traefik.enable=true" # 必填 否则无法加入traefik
      - "traefik.http.routers.apigw2.rule=Host(`apigw.guaosi.com`)" # 外部域名请求
      - "traefik.http.services.apigw2.loadbalancer.server.port=8092" # 转发至本容器指定port
networks:
  web:
    external:
      name: gomicro