version: '3'

services:
  proxy:
    image: traefik:v2.2
    container_name: traefik
    command: --api.insecure=true --providers.docker
    networks:
      - web
    ports:
      - "88:88"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml

networks:
  web:
    external:
      name: gomicro