// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReqAccountRegister struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqAccountRegister) Reset()         { *m = ReqAccountRegister{} }
func (m *ReqAccountRegister) String() string { return proto.CompactTextString(m) }
func (*ReqAccountRegister) ProtoMessage()    {}
func (*ReqAccountRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *ReqAccountRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqAccountRegister.Unmarshal(m, b)
}
func (m *ReqAccountRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqAccountRegister.Marshal(b, m, deterministic)
}
func (m *ReqAccountRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqAccountRegister.Merge(m, src)
}
func (m *ReqAccountRegister) XXX_Size() int {
	return xxx_messageInfo_ReqAccountRegister.Size(m)
}
func (m *ReqAccountRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqAccountRegister.DiscardUnknown(m)
}

var xxx_messageInfo_ReqAccountRegister proto.InternalMessageInfo

func (m *ReqAccountRegister) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ReqAccountRegister) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ResAccountRegister struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResAccountRegister) Reset()         { *m = ResAccountRegister{} }
func (m *ResAccountRegister) String() string { return proto.CompactTextString(m) }
func (*ResAccountRegister) ProtoMessage()    {}
func (*ResAccountRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *ResAccountRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResAccountRegister.Unmarshal(m, b)
}
func (m *ResAccountRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResAccountRegister.Marshal(b, m, deterministic)
}
func (m *ResAccountRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResAccountRegister.Merge(m, src)
}
func (m *ResAccountRegister) XXX_Size() int {
	return xxx_messageInfo_ResAccountRegister.Size(m)
}
func (m *ResAccountRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_ResAccountRegister.DiscardUnknown(m)
}

var xxx_messageInfo_ResAccountRegister proto.InternalMessageInfo

func (m *ResAccountRegister) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResAccountRegister) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqAccountRegister)(nil), "proto.ReqAccountRegister")
	proto.RegisterType((*ResAccountRegister)(nil), "proto.ResAccountRegister")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4c, 0x4e, 0xce,
	0x2f, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x3e, 0x5c,
	0x42, 0x41, 0xa9, 0x85, 0x8e, 0x10, 0xa9, 0xa0, 0xd4, 0xf4, 0xcc, 0xe2, 0x92, 0xd4, 0x22, 0x21,
	0x29, 0x2e, 0x8e, 0xd2, 0xe2, 0xd4, 0xa2, 0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d,
	0xce, 0x20, 0x38, 0x1f, 0x24, 0x57, 0x90, 0x58, 0x5c, 0x5c, 0x9e, 0x5f, 0x94, 0x22, 0xc1, 0x04,
	0x91, 0x83, 0xf1, 0x95, 0x9c, 0x40, 0xa6, 0x15, 0xa3, 0x9b, 0x26, 0xc4, 0xc5, 0x92, 0x9c, 0x9f,
	0x02, 0x31, 0x89, 0x35, 0x08, 0xcc, 0x16, 0x92, 0xe0, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c,
	0x4f, 0x85, 0x1a, 0x02, 0xe3, 0x1a, 0x45, 0x73, 0xf1, 0x41, 0x0d, 0x08, 0x4e, 0x2d, 0x2a, 0xcb,
	0x4c, 0x4e, 0x15, 0xf2, 0xe4, 0xe2, 0x47, 0x37, 0x52, 0x12, 0xe2, 0x0b, 0x3d, 0x4c, 0xb7, 0x4b,
	0x21, 0xa4, 0xd0, 0x1d, 0xa2, 0xc4, 0xe0, 0xc4, 0x19, 0xc5, 0xae, 0x67, 0x0d, 0x96, 0x4f, 0x62,
	0x03, 0x53, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9d, 0xb0, 0x26, 0x3e, 0x18, 0x01, 0x00,
	0x00,
}
